/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    ConnectionPanel: typeof import('./src/components/ConnectionPanel.vue')['default']
    DeviceListPanel: typeof import('./src/components/DeviceListPanel.vue')['default']
    MessageHistoryPanel: typeof import('./src/components/MessageHistoryPanel.vue')['default']
    MessageSendPanel: typeof import('./src/components/MessageSendPanel.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerConfigPanel: typeof import('./src/components/ServerConfigPanel.vue')['default']
    ServerInfoPanel: typeof import('./src/components/ServerInfoPanel.vue')['default']
  }
}
